language: scala
scala:
- 2.11.7
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database "akka-http-rest-test";' -U postgres
script: sbt test
deploy:
  provider: heroku
  api_key:
    secure: Q+NA/hHucsU9ZX1obGNcGS779NZhrwXuzGxR0bpkC6Lav0HxtK4ORz93cDahMEfofcK7d2YFMGvgbp8HqYuEyYHRZYuo54EJOpkCHsXEFdsLRrSn8bPGAPRxV0ToFdyBeBKfxwtHDW7frUMdJ0V3UKn5EstpAW0B8y1kyNlRXE+SKHFj1SObewz9UXRDtbVPZoDJrI2AhJS1iKL4dMYgvBEI9Q433oOnqUrsOKOYUZaWjEltxPUQ/mfOy8hzWha7sLRK3qMNAqvNy9WPgxfbJXXXbxlyqKICmgHP8vj7Vu173zpKgLMo+GtuEQIU835U8RXIRTUJjrw3YS85ojBhnyUiRAOSbU6xEcpbszwt66DLCsDZgPDDhHcLsuHyuchYySJE8056F4bZJu3ihTT7mAlqbeDiJjxzlN5oUIFmIxJ0oldW5RN+xwUcdY/KXI5dMSFf0HyzfhUW7DCSVpFkfJ2ljLy0oxmSHyW7ZmdmmYHPT8jfD0UvRaoEy3BE/uI0hzvBUf7OPc8RVGjFYBTQnUPqPWKd7VhxuEaUTbRtPxunCxjI6ghKBmzGLCgJGepnDiya5ZGqwkbNGqZFkg8HnMFGtLGDRwsTm3lZOKkht2Lyeq3BuQAc/BdaMsHVyXe45PqLMTLMqdwYLMhWXnouRN9AunUYjxWhORC3+3LV38A=